package com.ustc.wsn.mobileData.plot;

/**
 * Created by halo on 2018/1/21.
 */

/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int black=0x7f060000;
        public static final int dark_blue=0x7f060001;
        public static final int dark_green=0x7f060002;
        public static final int dark_orange=0x7f060003;
        public static final int dark_purple=0x7f060004;
        public static final int dark_red=0x7f060005;
        public static final int light_blue=0x7f060006;
        public static final int light_green=0x7f060007;
        public static final int light_orange=0x7f060008;
        public static final int light_purple=0x7f060009;
        public static final int light_red=0x7f06000a;
        public static final int mid_blue=0x7f06000b;
        public static final int mid_green=0x7f06000c;
        public static final int mid_orange=0x7f06000d;
        public static final int mid_purple=0x7f06000e;
        public static final int mid_red=0x7f06000f;
        public static final int white=0x7f060010;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f040000;
    }
    public static final class drawable {
        public static final int color_bar=0x7f020000;
        public static final int ic_launcher=0x7f020001;
        public static final int icon_logger=0x7f020002;
        public static final int ke_icon=0x7f020003;
        public static final int launcher_icon=0x7f020004;
    }
    public static final class id {
        public static final int ScrollView01=0x7f090000;
        public static final int check_box_lpf=0x7f09002f;
        public static final int check_box_mean_filter=0x7f090034;
        public static final int check_box_static_alpha=0x7f09003b;
        public static final int color_bar=0x7f090028;
        public static final int data_log_icon_layout=0x7f090025;
        public static final int data_rms_layout=0x7f090026;
        public static final int gauge_acceleration=0x7f09001e;
        public static final int gauge_acceleration_tilt=0x7f09001d;
        public static final int gauge_linear_acceleration=0x7f090024;
        public static final int gauge_linear_acceleration_tilt=0x7f090023;
        public static final int icon_logger=0x7f090027;
        public static final int image_color_bar=0x7f09002b;
        public static final int image_developer_icon=0x7f090029;
        public static final int label_acceleration_description=0x7f09001c;
        public static final int label_acceleration_name=0x7f09001b;
        public static final int label_acceleration_tilt=0x7f09001a;
        public static final int label_alpha_mode=0x7f09003a;
        public static final int label_app_description=0x7f090002;
        public static final int label_developer_description=0x7f09002a;
        public static final int label_filter_description=0x7f09000e;
        public static final int label_filter_name=0x7f09000d;
        public static final int label_lpf=0x7f09002e;
        public static final int label_lpf_description=0x7f090022;
        public static final int label_lpf_name=0x7f090021;
        public static final int label_lpf_tilt=0x7f090020;
        public static final int label_mean_filter=0x7f090033;
        public static final int label_sensor_name=0x7f090001;
        public static final int label_value=0x7f090037;
        public static final int label_x_axis=0x7f090012;
        public static final int label_y_axis=0x7f090014;
        public static final int label_z_axis=0x7f090016;
        public static final int layout_acceleration_tilt=0x7f090019;
        public static final int layout_lpf_checkbox=0x7f09002d;
        public static final int layout_lpf_tilt=0x7f09001f;
        public static final int layout_mean_filter_checkbox=0x7f090032;
        public static final int layout_set_lpf_values=0x7f090031;
        public static final int layout_set_mean_filter_values=0x7f090036;
        public static final int layout_settings_content=0x7f09002c;
        public static final int layout_statistics=0x7f09000f;
        public static final int layout_toggle_lpf_values=0x7f090030;
        public static final int layout_toggle_mean_filter_values=0x7f090035;
        public static final int menu_settings=0x7f09003c;
        public static final int menu_settings_filter=0x7f09003e;
        public static final int menu_settings_help=0x7f09003f;
        public static final int menu_settings_logger_plotdata=0x7f09003d;
        public static final int numberPicker1=0x7f090039;
        public static final int plot_sensor=0x7f090018;
        public static final int table_statistics_left=0x7f090010;
        public static final int table_statistics_left_row_0=0x7f090011;
        public static final int text_header_introduction_0=0x7f090003;
        public static final int text_header_introduction_1=0x7f090005;
        public static final int text_header_introduction_2=0x7f090007;
        public static final int text_header_introduction_3=0x7f090009;
        public static final int text_header_introduction_4=0x7f09000b;
        public static final int text_introduction_0=0x7f090004;
        public static final int text_introduction_1=0x7f090006;
        public static final int text_introduction_2=0x7f090008;
        public static final int text_introduction_3=0x7f09000a;
        public static final int text_introduction_4=0x7f09000c;
        public static final int value=0x7f090038;
        public static final int value_x_axis=0x7f090013;
        public static final int value_y_axis=0x7f090015;
        public static final int value_z_axis=0x7f090017;
    }
    public static final class layout {
        public static final int help=0x7f030000;
        public static final int plot_sensor_activity=0x7f030001;
        public static final int settings=0x7f030002;
        public static final int settings_filter=0x7f030003;
        public static final int settings_filter_set_value=0x7f030004;
        public static final int settings_toggle_set_value=0x7f030005;
    }
    public static final class menu {
        public static final int settings_logger_menu=0x7f080000;
    }
    public static final class string {
        public static final int acceleration_name=0x7f070000;
        public static final int action_settings=0x7f070001;
        public static final int app_name=0x7f070002;
        public static final int default_value=0x7f070003;
        public static final int developer_url=0x7f070004;
        public static final int dynamic_alpha=0x7f070005;
        public static final int filter_help=0x7f070006;
        public static final int filter_name=0x7f070007;
        public static final int filter_settings=0x7f070008;
        public static final int fusion_label=0x7f070009;
        public static final int label_value=0x7f07000a;
        public static final int log_data_label=0x7f07000b;
        public static final int low_pass_filter=0x7f07000c;
        public static final int mean_filter=0x7f07000d;
        public static final int rms_accel_label=0x7f07000e;
        public static final int rms_and_dev_label=0x7f07000f;
        public static final int rms_dynamic=0x7f070010;
        public static final int rms_static=0x7f070011;
        public static final int rms_wiki_label=0x7f070012;
        public static final int sensor_name=0x7f070013;
        public static final int simple_name=0x7f070014;
        public static final int static_alpha=0x7f070015;
    }
    public static final class style {
        /**  API 11 theme customizations can go here.
         API 14 theme customizations can go here.
         */
        public static final int AppBaseTheme=0x7f050000;
    }
}

